POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyNDY4YTRlZTIzYjA3NTgxNDVkMjNlOSIsImlhdCI6MTY0OTA5MjY1OCwiZXhwIjoxNjQ5MDk2MjU4fQ.Zr-iAJXeoqK1a8X-CBM9323tFHesqILwksfdQXtS-i4

{
  "title": "sample blog 24 ",
  "author": "sample author 24",
  "url": "https://sampleurl.com/sample",
  "likes": 12
}