POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MjQ2OGI2ZjljZTI1OWJjMjUxZmJhZDUiLCJpYXQiOjE2NDk0OTgxMzUsImV4cCI6MTY0OTUwMTczNX0.jTUM1O0Ah3HBaKaoho1bqDNRINczugQDMiK3MBqMWjI

{
  "title": "Microservices and the First Law of Distributed Objects",
  "author": "Martin Fowler",
  "url": "https://www.martinfowler.com/articles/distributed-objects-microservices.html",
  "likes": 3
}